### ISSUE TITLE
Generate endpoint link causes the SSO component to reload

### ISSUE THREAD

**Issue by dgutride** [rhuxd-mfe-poc/3scale#3] opened 2020-09-08 14:18 UTC
The generate endpoint link has been reloading the sso component for some reason.

**Comment by redallen** [comment] 2020-09-08 17:02
Duplicate of #1

**Comment by redallen** [comment] 2020-09-08 17:03
Whoops, not a duplicate.

Fixed in https://github.com/rhuxd-mfe-poc/3scale/commit/837b8446fd6ae95a53d60b815ac98270822f2d72

**Closed as completed by redallen** 2020-09-08 17:02 UTC
